"""Paddlemetrics functional API."""

from paddlemetrics.functional.audio import (
    complex_scale_invariant_signal_noise_ratio,
    permutation_invariant_training,
    pit_permutate,
    scale_invariant_signal_distortion_ratio,
    scale_invariant_signal_noise_ratio,
    signal_distortion_ratio,
    signal_noise_ratio,
    source_aggregated_signal_distortion_ratio,
)
from paddlemetrics.functional.classification import (
    accuracy,
    auroc,
    average_precision,
    calibration_error,
    cohen_kappa,
    confusion_matrix,
    eer,
    exact_match,
    f1_score,
    fbeta_score,
    hamming_distance,
    hinge_loss,
    jaccard_index,
    logauc,
    matthews_corrcoef,
    negative_predictive_value,
    precision,
    precision_at_fixed_recall,
    precision_recall_curve,
    recall,
    recall_at_fixed_precision,
    roc,
    sensitivity_at_specificity,
    specificity,
    specificity_at_sensitivity,
    stat_scores,
)
from paddlemetrics.functional.clustering import (
    adjusted_mutual_info_score,
    adjusted_rand_score,
    calinski_harabasz_score,
    cluster_accuracy,
    completeness_score,
    davies_bouldin_score,
    dunn_index,
    fowlkes_mallows_index,
    homogeneity_score,
    mutual_info_score,
    normalized_mutual_info_score,
    rand_score,
    v_measure_score,
)
from paddlemetrics.functional.detection import (
    modified_panoptic_quality,
    panoptic_quality,
)
from paddlemetrics.functional.image import (
    error_relative_global_dimensionless_synthesis,
    image_gradients,
    multiscale_structural_similarity_index_measure,
    peak_signal_noise_ratio,
    peak_signal_noise_ratio_with_blocked_effect,
    relative_average_spectral_error,
    root_mean_squared_error_using_sliding_window,
    spatial_correlation_coefficient,
    spectral_angle_mapper,
    spectral_distortion_index,
    structural_similarity_index_measure,
    total_variation,
    universal_image_quality_index,
    visual_information_fidelity,
)
from paddlemetrics.functional.multimodal import lip_vertex_error
from paddlemetrics.functional.nominal import (
    cramers_v,
    cramers_v_matrix,
    fleiss_kappa,
    pearsons_contingency_coefficient,
    pearsons_contingency_coefficient_matrix,
    theils_u,
    theils_u_matrix,
    tschuprows_t,
    tschuprows_t_matrix,
)
from paddlemetrics.functional.pairwise import (
    pairwise_cosine_similarity,
    pairwise_euclidean_distance,
    pairwise_linear_similarity,
    pairwise_manhattan_distance,
    pairwise_minkowski_distance,
)
from paddlemetrics.functional.regression import (
    concordance_corrcoef,
    continuous_ranked_probability_score,
    cosine_similarity,
    critical_success_index,
    explained_variance,
    jensen_shannon_divergence,
    kendall_rank_corrcoef,
    kl_divergence,
    log_cosh_error,
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_error,
    mean_squared_log_error,
    minkowski_distance,
    normalized_root_mean_squared_error,
    pearson_corrcoef,
    r2_score,
    relative_squared_error,
    spearman_corrcoef,
    symmetric_mean_absolute_percentage_error,
    tweedie_deviance_score,
    weighted_mean_absolute_percentage_error,
)
from paddlemetrics.functional.retrieval import (
    retrieval_auroc,
    retrieval_average_precision,
    retrieval_fall_out,
    retrieval_hit_rate,
    retrieval_normalized_dcg,
    retrieval_precision,
    retrieval_precision_recall_curve,
    retrieval_r_precision,
    retrieval_recall,
    retrieval_reciprocal_rank,
)
from paddlemetrics.functional.segmentation import (
    dice_score,
    generalized_dice_score,
    hausdorff_distance,
    mean_iou,
)
from paddlemetrics.functional.shape import procrustes_disparity
from paddlemetrics.functional.text import (
    bleu_score,
    char_error_rate,
    chrf_score,
    edit_distance,
    extended_edit_distance,
    match_error_rate,
    perplexity,
    rouge_score,
    sacre_bleu_score,
    squad,
    translation_edit_rate,
    word_error_rate,
    word_information_lost,
    word_information_preserved,
)

__all__ = [
    # Audio
    "complex_scale_invariant_signal_noise_ratio",
    "permutation_invariant_training",
    "pit_permutate",
    "scale_invariant_signal_distortion_ratio",
    "scale_invariant_signal_noise_ratio",
    "signal_distortion_ratio",
    "signal_noise_ratio",
    "source_aggregated_signal_distortion_ratio",
    # Classification
    "accuracy",
    "auroc",
    "average_precision",
    "calibration_error",
    "cohen_kappa",
    "confusion_matrix",
    "eer",
    "exact_match",
    "f1_score",
    "fbeta_score",
    "hamming_distance",
    "hinge_loss",
    "jaccard_index",
    "logauc",
    "matthews_corrcoef",
    "negative_predictive_value",
    "precision",
    "precision_at_fixed_recall",
    "precision_recall_curve",
    "recall",
    "recall_at_fixed_precision",
    "roc",
    "sensitivity_at_specificity",
    "specificity",
    "specificity_at_sensitivity",
    "stat_scores",
    # Clustering
    "adjusted_mutual_info_score",
    "adjusted_rand_score",
    "calinski_harabasz_score",
    "cluster_accuracy",
    "completeness_score",
    "davies_bouldin_score",
    "dunn_index",
    "fowlkes_mallows_index",
    "homogeneity_score",
    "mutual_info_score",
    "normalized_mutual_info_score",
    "rand_score",
    "v_measure_score",
    # Detection
    "modified_panoptic_quality",
    "panoptic_quality",
    # Image
    "error_relative_global_dimensionless_synthesis",
    "image_gradients",
    "multiscale_structural_similarity_index_measure",
    "peak_signal_noise_ratio",
    "peak_signal_noise_ratio_with_blocked_effect",
    "relative_average_spectral_error",
    "root_mean_squared_error_using_sliding_window",
    "spatial_correlation_coefficient",
    "spectral_angle_mapper",
    "spectral_distortion_index",
    "structural_similarity_index_measure",
    "total_variation",
    "universal_image_quality_index",
    "visual_information_fidelity",
    # Multimodal
    "lip_vertex_error",
    # Nominal
    "cramers_v",
    "cramers_v_matrix",
    "fleiss_kappa",
    "pearsons_contingency_coefficient",
    "pearsons_contingency_coefficient_matrix",
    "theils_u",
    "theils_u_matrix",
    "tschuprows_t",
    "tschuprows_t_matrix",
    # Pairwise
    "pairwise_cosine_similarity",
    "pairwise_euclidean_distance",
    "pairwise_linear_similarity",
    "pairwise_manhattan_distance",
    "pairwise_minkowski_distance",
    # Regression
    "concordance_corrcoef",
    "continuous_ranked_probability_score",
    "cosine_similarity",
    "critical_success_index",
    "explained_variance",
    "jensen_shannon_divergence",
    "kendall_rank_corrcoef",
    "kl_divergence",
    "log_cosh_error",
    "mean_absolute_error",
    "mean_absolute_percentage_error",
    "mean_squared_error",
    "mean_squared_log_error",
    "minkowski_distance",
    "normalized_root_mean_squared_error",
    "pearson_corrcoef",
    "r2_score",
    "relative_squared_error",
    "spearman_corrcoef",
    "symmetric_mean_absolute_percentage_error",
    "tweedie_deviance_score",
    "weighted_mean_absolute_percentage_error",
    # Retrieval
    "retrieval_auroc",
    "retrieval_average_precision",
    "retrieval_fall_out",
    "retrieval_hit_rate",
    "retrieval_normalized_dcg",
    "retrieval_precision",
    "retrieval_precision_recall_curve",
    "retrieval_r_precision",
    "retrieval_recall",
    "retrieval_reciprocal_rank",
    # Segmentation
    "dice_score",
    "generalized_dice_score",
    "hausdorff_distance",
    "mean_iou",
    # Shape
    "procrustes_disparity",
    # Text
    "bleu_score",
    "char_error_rate",
    "chrf_score",
    "edit_distance",
    "extended_edit_distance",
    "match_error_rate",
    "perplexity",
    "rouge_score",
    "sacre_bleu_score",
    "squad",
    "translation_edit_rate",
    "word_error_rate",
    "word_information_lost",
    "word_information_preserved",
]
