"""Paddlemetrics functional API."""
from paddlemetrics.functional.classification import (
    accuracy,
    auroc,
    average_precision,
    calibration_error,
    cohen_kappa,
    confusion_matrix,
    eer,
    exact_match,
    f1_score,
    fbeta_score,
    hamming_distance,
    hinge_loss,
    jaccard_index,
    logauc,
    matthews_corrcoef,
    negative_predictive_value,
    precision,
    precision_at_fixed_recall,
    precision_recall_curve,
    recall,
    recall_at_fixed_precision,
    roc,
    sensitivity_at_specificity,
    specificity,
    specificity_at_sensitivity,
    stat_scores,
)

__all__ = [
    "accuracy", "auroc", "average_precision", "calibration_error",
    "cohen_kappa", "confusion_matrix", "eer", "exact_match",
    "f1_score", "fbeta_score", "hamming_distance", "hinge_loss",
    "jaccard_index", "logauc", "matthews_corrcoef",
    "negative_predictive_value", "precision", "precision_at_fixed_recall",
    "precision_recall_curve", "recall", "recall_at_fixed_precision",
    "roc", "sensitivity_at_specificity", "specificity",
    "specificity_at_sensitivity", "stat_scores",
]
